// =====================================================================
// TPO Ingenieria de Datos II - 1er cuatrimestre 2026
// MongoDB seed: insert cliente documents with their embedded telefonos.
//
// IMPORTANT: nro_cliente values must match those used in factura.nro_cliente
// in sql/02-seed.sql so that cross-DB queries (reqs 4, 5, 6, 7, 10) work.
//
// Idempotent: clears the collection before inserting (keeps validator and
// indexes from 01-setup.js intact).
//
// Run with:
//   mongosh "mongodb://localhost:27017/tpo_facturacion" --file 02-seed.js
// =====================================================================

// === Clean previous data (preserves collection + validator + indexes) ===
db.cliente.deleteMany({});

// === Insert clientes ===
db.cliente.insertMany([
    { nro_cliente: NumberInt(1), nombre: "Xerxes", apellido: "Hale", direccion: "129-5974 Suspendisse Ctra.", activo: NumberInt(89), telefonos: [ { codigo_area: NumberInt(513), nro_telefono: NumberInt(4998612), tipo: "M" }, { codigo_area: NumberInt(992), nro_telefono: NumberInt(4241515), tipo: "F" } ] },
    { nro_cliente: NumberInt(2), nombre: "Brent", apellido: "Leblanc", direccion: "Apartado núm.: 372, 5244 Nibh.", activo: NumberInt(58), telefonos: [ { codigo_area: NumberInt(638), nro_telefono: NumberInt(4819478), tipo: "F" } ] },
    { nro_cliente: NumberInt(3), nombre: "Kasper", apellido: "Shannon", direccion: "Apdo.:304-6908 Class Ctra.", activo: NumberInt(38), telefonos: [ { codigo_area: NumberInt(915), nro_telefono: NumberInt(4686947), tipo: "F" } ] },
    { nro_cliente: NumberInt(4), nombre: "Pandora", apellido: "Tate", direccion: "1221 Egestas. Carretera", activo: NumberInt(124), telefonos: [] },
    { nro_cliente: NumberInt(5), nombre: "Kai", apellido: "Bullock", direccion: "Apdo.:796-1402 Diam Calle", activo: NumberInt(60), telefonos: [ { codigo_area: NumberInt(662), nro_telefono: NumberInt(4466147), tipo: "M" } ] },
    { nro_cliente: NumberInt(6), nombre: "Calvin", apellido: "Hyde", direccion: "Apdo.:777-9475 Quam Avda.", activo: NumberInt(66), telefonos: [] },
    { nro_cliente: NumberInt(7), nombre: "Rina", apellido: "Brennan", direccion: "Apdo.:184-1212 Accumsan C.", activo: NumberInt(14), telefonos: [ { codigo_area: NumberInt(158), nro_telefono: NumberInt(4583134), tipo: "M" }, { codigo_area: NumberInt(351), nro_telefono: NumberInt(4268273), tipo: "M" } ] },
    { nro_cliente: NumberInt(8), nombre: "Mari", apellido: "Savage", direccion: "2062 Id Avenida", activo: NumberInt(49), telefonos: [ { codigo_area: NumberInt(132), nro_telefono: NumberInt(4962172), tipo: "F" }, { codigo_area: NumberInt(212), nro_telefono: NumberInt(4515936), tipo: "F" }, { codigo_area: NumberInt(629), nro_telefono: NumberInt(4699941), tipo: "F" } ] },
    { nro_cliente: NumberInt(9), nombre: "Azalia", apellido: "Estes", direccion: "3801 Sed Ctra.", activo: NumberInt(56), telefonos: [ { codigo_area: NumberInt(172), nro_telefono: NumberInt(4344579), tipo: "M" } ] },
    { nro_cliente: NumberInt(10), nombre: "Ivor", apellido: "Saunders", direccion: "4432 Nisl Avenida", activo: NumberInt(121), telefonos: [ { codigo_area: NumberInt(189), nro_telefono: NumberInt(4229129), tipo: "F" } ] },
    { nro_cliente: NumberInt(11), nombre: "Lane", apellido: "Alvarado", direccion: "441-7608 Dis Avenida", activo: NumberInt(25), telefonos: [ { codigo_area: NumberInt(115), nro_telefono: NumberInt(4573879), tipo: "F" } ] },
    { nro_cliente: NumberInt(12), nombre: "Melvin", apellido: "Hubbard", direccion: "5483 Dictum Ctra.", activo: NumberInt(81), telefonos: [ { codigo_area: NumberInt(146), nro_telefono: NumberInt(4579375), tipo: "F" }, { codigo_area: NumberInt(336), nro_telefono: NumberInt(4869818), tipo: "M" }, { codigo_area: NumberInt(698), nro_telefono: NumberInt(4653876), tipo: "F" }, { codigo_area: NumberInt(712), nro_telefono: NumberInt(4652912), tipo: "F" } ] },
    { nro_cliente: NumberInt(13), nombre: "Miranda", apellido: "Knowles", direccion: "500-3176 Ligula", activo: NumberInt(22), telefonos: [ { codigo_area: NumberInt(491), nro_telefono: NumberInt(4639673), tipo: "F" }, { codigo_area: NumberInt(694), nro_telefono: NumberInt(4485437), tipo: "F" } ] },
    { nro_cliente: NumberInt(14), nombre: "Ayanna", apellido: "Lara", direccion: "236-8958 Magna Avenida", activo: NumberInt(52), telefonos: [ { codigo_area: NumberInt(546), nro_telefono: NumberInt(4275735), tipo: "F" } ] },
    { nro_cliente: NumberInt(15), nombre: "Clio", apellido: "Phelps", direccion: "Apdo.:139-2362 Fermentum C/", activo: NumberInt(14), telefonos: [ { codigo_area: NumberInt(266), nro_telefono: NumberInt(4938182), tipo: "F" }, { codigo_area: NumberInt(494), nro_telefono: NumberInt(4256865), tipo: "F" }, { codigo_area: NumberInt(772), nro_telefono: NumberInt(4299982), tipo: "F" } ] },
    { nro_cliente: NumberInt(16), nombre: "Richard", apellido: "Burch", direccion: "Apartado núm.: 682, 8150 Eu Avenida", activo: NumberInt(42), telefonos: [ { codigo_area: NumberInt(581), nro_telefono: NumberInt(4369984), tipo: "M" }, { codigo_area: NumberInt(599), nro_telefono: NumberInt(4349389), tipo: "M" }, { codigo_area: NumberInt(717), nro_telefono: NumberInt(4117747), tipo: "M" } ] },
    { nro_cliente: NumberInt(17), nombre: "Deirdre", apellido: "Wilkinson", direccion: "Apartado núm.: 390, 1800 Penatibus Carretera", activo: NumberInt(122), telefonos: [ { codigo_area: NumberInt(729), nro_telefono: NumberInt(4228712), tipo: "F" }, { codigo_area: NumberInt(734), nro_telefono: NumberInt(4571175), tipo: "M" } ] },
    { nro_cliente: NumberInt(18), nombre: "Wendy", apellido: "Stokes", direccion: "Apdo.:853-5716 Eget, Carretera", activo: NumberInt(123), telefonos: [ { codigo_area: NumberInt(413), nro_telefono: NumberInt(4994492), tipo: "F" }, { codigo_area: NumberInt(515), nro_telefono: NumberInt(4513942), tipo: "M" }, { codigo_area: NumberInt(854), nro_telefono: NumberInt(4162434), tipo: "F" } ] },
    { nro_cliente: NumberInt(19), nombre: "Merrill", apellido: "Allen", direccion: "4958 Vitae Avda.", activo: NumberInt(98), telefonos: [ { codigo_area: NumberInt(221), nro_telefono: NumberInt(4129231), tipo: "M" }, { codigo_area: NumberInt(293), nro_telefono: NumberInt(4265431), tipo: "F" }, { codigo_area: NumberInt(518), nro_telefono: NumberInt(4547153), tipo: "F" }, { codigo_area: NumberInt(737), nro_telefono: NumberInt(4961183), tipo: "F" } ] },
    { nro_cliente: NumberInt(20), nombre: "Barclay", apellido: "Valenzuela", direccion: "Apdo.:353-8666 Faucibus Calle", activo: NumberInt(63), telefonos: [ { codigo_area: NumberInt(624), nro_telefono: NumberInt(4263377), tipo: "M" }, { codigo_area: NumberInt(721), nro_telefono: NumberInt(4757253), tipo: "F" }, { codigo_area: NumberInt(934), nro_telefono: NumberInt(4741992), tipo: "F" } ] },
    { nro_cliente: NumberInt(21), nombre: "Anjolie", apellido: "Soto", direccion: "1138 Amet Ctra.", activo: NumberInt(77), telefonos: [ { codigo_area: NumberInt(716), nro_telefono: NumberInt(4156525), tipo: "M" } ] },
    { nro_cliente: NumberInt(22), nombre: "Jacob", apellido: "Cooper", direccion: "Apartado núm.: 268, 1455 Volutpat", activo: NumberInt(92), telefonos: [ { codigo_area: NumberInt(178), nro_telefono: NumberInt(4758526), tipo: "M" }, { codigo_area: NumberInt(323), nro_telefono: NumberInt(4481471), tipo: "F" }, { codigo_area: NumberInt(416), nro_telefono: NumberInt(4855972), tipo: "F" }, { codigo_area: NumberInt(551), nro_telefono: NumberInt(4972222), tipo: "M" }, { codigo_area: NumberInt(577), nro_telefono: NumberInt(4473896), tipo: "F" }, { codigo_area: NumberInt(844), nro_telefono: NumberInt(4699112), tipo: "M" }, { codigo_area: NumberInt(871), nro_telefono: NumberInt(4368415), tipo: "F" } ] },
    { nro_cliente: NumberInt(23), nombre: "Drew", apellido: "Boyle", direccion: "663-3481 Nisl. Ctra.", activo: NumberInt(88), telefonos: [ { codigo_area: NumberInt(842), nro_telefono: NumberInt(4848273), tipo: "F" } ] },
    { nro_cliente: NumberInt(24), nombre: "Kermit", apellido: "Dorsey", direccion: "4946 Consectetuer Carretera", activo: NumberInt(4), telefonos: [] },
    { nro_cliente: NumberInt(25), nombre: "Galvin", apellido: "Summers", direccion: "757-9907 Natoque", activo: NumberInt(102), telefonos: [ { codigo_area: NumberInt(649), nro_telefono: NumberInt(4975485), tipo: "F" } ] },
    { nro_cliente: NumberInt(26), nombre: "Daniel", apellido: "Frye", direccion: "2404 Sodales Calle", activo: NumberInt(88), telefonos: [ { codigo_area: NumberInt(698), nro_telefono: NumberInt(4499482), tipo: "M" } ] },
    { nro_cliente: NumberInt(27), nombre: "Mason", apellido: "Swanson", direccion: "Apdo.:147-8872 Dolor, Av.", activo: NumberInt(108), telefonos: [ { codigo_area: NumberInt(612), nro_telefono: NumberInt(4788261), tipo: "F" }, { codigo_area: NumberInt(964), nro_telefono: NumberInt(4177915), tipo: "M" } ] },
    { nro_cliente: NumberInt(28), nombre: "Brady", apellido: "Burgess", direccion: "Apdo.:912-3139 Ante C.", activo: NumberInt(82), telefonos: [ { codigo_area: NumberInt(937), nro_telefono: NumberInt(4981317), tipo: "F" } ] },
    { nro_cliente: NumberInt(29), nombre: "Oscar", apellido: "Merrill", direccion: "Apdo.:341-991 Parturient", activo: NumberInt(2), telefonos: [ { codigo_area: NumberInt(744), nro_telefono: NumberInt(4216131), tipo: "M" } ] },
    { nro_cliente: NumberInt(30), nombre: "Constance", apellido: "Sweeney", direccion: "Apartado núm.: 158, 9519 Tincidunt Avenida", activo: NumberInt(92), telefonos: [ { codigo_area: NumberInt(225), nro_telefono: NumberInt(4958119), tipo: "F" }, { codigo_area: NumberInt(425), nro_telefono: NumberInt(4989475), tipo: "F" }, { codigo_area: NumberInt(826), nro_telefono: NumberInt(4499636), tipo: "F" } ] },
    { nro_cliente: NumberInt(31), nombre: "Jescie", apellido: "Wong", direccion: "Apartado núm.: 467, 878 Id, Avenida", activo: NumberInt(40), telefonos: [] },
    { nro_cliente: NumberInt(32), nombre: "Jade", apellido: "Garrison", direccion: "6341 Sit C.", activo: NumberInt(11), telefonos: [ { codigo_area: NumberInt(122), nro_telefono: NumberInt(4287757), tipo: "M" }, { codigo_area: NumberInt(242), nro_telefono: NumberInt(4474281), tipo: "M" }, { codigo_area: NumberInt(598), nro_telefono: NumberInt(4922572), tipo: "F" } ] },
    { nro_cliente: NumberInt(33), nombre: "Cameran", apellido: "Levine", direccion: "Apartado núm.: 187, 2941 Eu C.", activo: NumberInt(1), telefonos: [ { codigo_area: NumberInt(845), nro_telefono: NumberInt(4727859), tipo: "F" }, { codigo_area: NumberInt(934), nro_telefono: NumberInt(4691792), tipo: "F" }, { codigo_area: NumberInt(947), nro_telefono: NumberInt(4359678), tipo: "M" } ] },
    { nro_cliente: NumberInt(34), nombre: "Alexandra", apellido: "Noel", direccion: "Apartado núm.: 664, 2069 A, Av.", activo: NumberInt(81), telefonos: [ { codigo_area: NumberInt(391), nro_telefono: NumberInt(4959995), tipo: "M" } ] },
    { nro_cliente: NumberInt(35), nombre: "Melissa", apellido: "Mccormick", direccion: "8306 Quisque Avda.", activo: NumberInt(59), telefonos: [ { codigo_area: NumberInt(133), nro_telefono: NumberInt(4821891), tipo: "F" }, { codigo_area: NumberInt(766), nro_telefono: NumberInt(4997692), tipo: "M" } ] },
    { nro_cliente: NumberInt(36), nombre: "Kelsie", apellido: "Oneill", direccion: "6019 Mauris, Carretera", activo: NumberInt(124), telefonos: [] },
    { nro_cliente: NumberInt(37), nombre: "Chandler", apellido: "Parrish", direccion: "Apdo.:527-3025 A Av.", activo: NumberInt(15), telefonos: [ { codigo_area: NumberInt(138), nro_telefono: NumberInt(4743285), tipo: "F" }, { codigo_area: NumberInt(243), nro_telefono: NumberInt(4514757), tipo: "F" }, { codigo_area: NumberInt(714), nro_telefono: NumberInt(4688314), tipo: "F" } ] },
    { nro_cliente: NumberInt(38), nombre: "Hayes", apellido: "Pollard", direccion: "398-1678 Mattis. C.", activo: NumberInt(116), telefonos: [ { codigo_area: NumberInt(156), nro_telefono: NumberInt(4918587), tipo: "M" }, { codigo_area: NumberInt(625), nro_telefono: NumberInt(4232149), tipo: "F" } ] },
    { nro_cliente: NumberInt(39), nombre: "Anthony", apellido: "Rose", direccion: "412-4773 Interdum Ctra.", activo: NumberInt(57), telefonos: [] },
    { nro_cliente: NumberInt(40), nombre: "Whoopi", apellido: "Herring", direccion: "869 Quisque C.", activo: NumberInt(86), telefonos: [ { codigo_area: NumberInt(181), nro_telefono: NumberInt(4416386), tipo: "M" }, { codigo_area: NumberInt(584), nro_telefono: NumberInt(4239611), tipo: "F" }, { codigo_area: NumberInt(644), nro_telefono: NumberInt(4862538), tipo: "M" } ] },
    { nro_cliente: NumberInt(41), nombre: "Maryam", apellido: "Miranda", direccion: "Apdo.:866-8040 Integer Calle", activo: NumberInt(57), telefonos: [ { codigo_area: NumberInt(425), nro_telefono: NumberInt(4866573), tipo: "M" } ] },
    { nro_cliente: NumberInt(42), nombre: "Linus", apellido: "Potts", direccion: "Apdo.:858-6434 Luctus. Calle", activo: NumberInt(49), telefonos: [ { codigo_area: NumberInt(193), nro_telefono: NumberInt(4625992), tipo: "F" }, { codigo_area: NumberInt(296), nro_telefono: NumberInt(4416716), tipo: "F" }, { codigo_area: NumberInt(712), nro_telefono: NumberInt(4261611), tipo: "F" }, { codigo_area: NumberInt(734), nro_telefono: NumberInt(4591721), tipo: "M" } ] },
    { nro_cliente: NumberInt(43), nombre: "Chancellor", apellido: "Roy", direccion: "Apartado núm.: 584, 2262 Malesuada", activo: NumberInt(56), telefonos: [ { codigo_area: NumberInt(567), nro_telefono: NumberInt(4226771), tipo: "F" }, { codigo_area: NumberInt(895), nro_telefono: NumberInt(4647454), tipo: "M" } ] },
    { nro_cliente: NumberInt(44), nombre: "Lana", apellido: "Gallagher", direccion: "Apdo.:446-7104 Lectus Avenida", activo: NumberInt(29), telefonos: [ { codigo_area: NumberInt(764), nro_telefono: NumberInt(4351784), tipo: "F" }, { codigo_area: NumberInt(843), nro_telefono: NumberInt(4442328), tipo: "F" } ] },
    { nro_cliente: NumberInt(45), nombre: "Azalia", apellido: "Tyson", direccion: "205-2990 Quam C.", activo: NumberInt(16), telefonos: [ { codigo_area: NumberInt(537), nro_telefono: NumberInt(4712565), tipo: "F" }, { codigo_area: NumberInt(658), nro_telefono: NumberInt(4676748), tipo: "F" }, { codigo_area: NumberInt(767), nro_telefono: NumberInt(4198968), tipo: "M" }, { codigo_area: NumberInt(776), nro_telefono: NumberInt(4156887), tipo: "F" } ] },
    { nro_cliente: NumberInt(46), nombre: "Suki", apellido: "Copeland", direccion: "Apdo.:427-9736 Integer Calle", activo: NumberInt(107), telefonos: [ { codigo_area: NumberInt(933), nro_telefono: NumberInt(4245265), tipo: "F" } ] },
    { nro_cliente: NumberInt(47), nombre: "Zorita", apellido: "Campbell", direccion: "576-8561 Quis Ctra.", activo: NumberInt(83), telefonos: [ { codigo_area: NumberInt(779), nro_telefono: NumberInt(4916857), tipo: "M" }, { codigo_area: NumberInt(781), nro_telefono: NumberInt(4872881), tipo: "F" }, { codigo_area: NumberInt(984), nro_telefono: NumberInt(4518627), tipo: "F" } ] },
    { nro_cliente: NumberInt(48), nombre: "Uriah", apellido: "Morton", direccion: "853-9564 Eu C/", activo: NumberInt(82), telefonos: [ { codigo_area: NumberInt(239), nro_telefono: NumberInt(4889238), tipo: "F" }, { codigo_area: NumberInt(321), nro_telefono: NumberInt(4112993), tipo: "M" }, { codigo_area: NumberInt(352), nro_telefono: NumberInt(4261374), tipo: "M" } ] },
    { nro_cliente: NumberInt(49), nombre: "Jescie", apellido: "Daugherty", direccion: "788-9186 Mattis C/", activo: NumberInt(55), telefonos: [ { codigo_area: NumberInt(372), nro_telefono: NumberInt(4533785), tipo: "M" }, { codigo_area: NumberInt(526), nro_telefono: NumberInt(4493917), tipo: "M" }, { codigo_area: NumberInt(664), nro_telefono: NumberInt(4892549), tipo: "M" } ] },
    { nro_cliente: NumberInt(50), nombre: "Charde", apellido: "Kinney", direccion: "7770 Pharetra. Avenida", activo: NumberInt(39), telefonos: [ { codigo_area: NumberInt(336), nro_telefono: NumberInt(4746844), tipo: "F" }, { codigo_area: NumberInt(376), nro_telefono: NumberInt(4692515), tipo: "M" }, { codigo_area: NumberInt(571), nro_telefono: NumberInt(4162696), tipo: "F" }, { codigo_area: NumberInt(656), nro_telefono: NumberInt(4537796), tipo: "F" }, { codigo_area: NumberInt(666), nro_telefono: NumberInt(4714359), tipo: "F" }, { codigo_area: NumberInt(678), nro_telefono: NumberInt(4316261), tipo: "M" }, { codigo_area: NumberInt(798), nro_telefono: NumberInt(4342943), tipo: "M" } ] },
    { nro_cliente: NumberInt(51), nombre: "Candice", apellido: "Ramos", direccion: "Apartado núm.: 247, 103 Neque Avda.", activo: NumberInt(52), telefonos: [ { codigo_area: NumberInt(551), nro_telefono: NumberInt(4538279), tipo: "F" } ] },
    { nro_cliente: NumberInt(52), nombre: "Wanda", apellido: "Baker", direccion: "4394 Faucibus Calle", activo: NumberInt(44), telefonos: [ { codigo_area: NumberInt(313), nro_telefono: NumberInt(4578765), tipo: "F" }, { codigo_area: NumberInt(593), nro_telefono: NumberInt(4118559), tipo: "F" } ] },
    { nro_cliente: NumberInt(53), nombre: "Quyn", apellido: "Bernard", direccion: "4923 Suscipit C.", activo: NumberInt(27), telefonos: [] },
    { nro_cliente: NumberInt(54), nombre: "Laura", apellido: "Norton", direccion: "Apartado núm.: 940, 3935 Pede.", activo: NumberInt(99), telefonos: [ { codigo_area: NumberInt(917), nro_telefono: NumberInt(4586231), tipo: "M" } ] },
    { nro_cliente: NumberInt(55), nombre: "Camden", apellido: "Casey", direccion: "4816 Magna Ctra.", activo: NumberInt(52), telefonos: [ { codigo_area: NumberInt(954), nro_telefono: NumberInt(4519446), tipo: "F" } ] },
    { nro_cliente: NumberInt(56), nombre: "Darius", apellido: "Myers", direccion: "6187 Eu, Ctra.", activo: NumberInt(15), telefonos: [ { codigo_area: NumberInt(653), nro_telefono: NumberInt(4836337), tipo: "F" } ] },
    { nro_cliente: NumberInt(57), nombre: "Cecilia", apellido: "Morgan", direccion: "250-9117 Amet C/", activo: NumberInt(45), telefonos: [ { codigo_area: NumberInt(145), nro_telefono: NumberInt(4353693), tipo: "F" }, { codigo_area: NumberInt(158), nro_telefono: NumberInt(4478676), tipo: "F" }, { codigo_area: NumberInt(297), nro_telefono: NumberInt(4129464), tipo: "F" } ] },
    { nro_cliente: NumberInt(58), nombre: "Kaye", apellido: "Stokes", direccion: "Apdo.:227-9814 Natoque Carretera", activo: NumberInt(27), telefonos: [ { codigo_area: NumberInt(428), nro_telefono: NumberInt(4354331), tipo: "M" }, { codigo_area: NumberInt(684), nro_telefono: NumberInt(4541672), tipo: "M" }, { codigo_area: NumberInt(776), nro_telefono: NumberInt(4552842), tipo: "F" } ] },
    { nro_cliente: NumberInt(59), nombre: "Rebekah", apellido: "Cooke", direccion: "795-1037 Est Carretera", activo: NumberInt(53), telefonos: [ { codigo_area: NumberInt(446), nro_telefono: NumberInt(4677526), tipo: "M" }, { codigo_area: NumberInt(756), nro_telefono: NumberInt(4646842), tipo: "M" } ] },
    { nro_cliente: NumberInt(60), nombre: "Willow", apellido: "Herman", direccion: "156-7871 Mauris Av.", activo: NumberInt(96), telefonos: [] },
    { nro_cliente: NumberInt(61), nombre: "Tanya", apellido: "Reynolds", direccion: "Apdo.:930-5715 Pede C/", activo: NumberInt(125), telefonos: [] },
    { nro_cliente: NumberInt(62), nombre: "Ursula", apellido: "Pollard", direccion: "971-7618 Tristique Carretera", activo: NumberInt(118), telefonos: [ { codigo_area: NumberInt(442), nro_telefono: NumberInt(4761113), tipo: "F" }, { codigo_area: NumberInt(629), nro_telefono: NumberInt(4143491), tipo: "F" } ] },
    { nro_cliente: NumberInt(63), nombre: "Uriel", apellido: "Lancaster", direccion: "Apdo.:954-3051 Scelerisque Calle", activo: NumberInt(87), telefonos: [ { codigo_area: NumberInt(384), nro_telefono: NumberInt(4181452), tipo: "M" } ] },
    { nro_cliente: NumberInt(64), nombre: "Cruz", apellido: "Meyer", direccion: "Apartado núm.: 688, 7346 Sit Avenida", activo: NumberInt(76), telefonos: [] },
    { nro_cliente: NumberInt(65), nombre: "Ciaran", apellido: "Langley", direccion: "237-1249 Fusce Avenida", activo: NumberInt(37), telefonos: [ { codigo_area: NumberInt(259), nro_telefono: NumberInt(4899357), tipo: "M" }, { codigo_area: NumberInt(894), nro_telefono: NumberInt(4313689), tipo: "F" }, { codigo_area: NumberInt(911), nro_telefono: NumberInt(4321977), tipo: "F" } ] },
    { nro_cliente: NumberInt(66), nombre: "Tasha", apellido: "Robbins", direccion: "Apartado núm.: 283, 4035 Fusce Carretera", activo: NumberInt(105), telefonos: [ { codigo_area: NumberInt(486), nro_telefono: NumberInt(4422312), tipo: "M" }, { codigo_area: NumberInt(735), nro_telefono: NumberInt(4972978), tipo: "F" } ] },
    { nro_cliente: NumberInt(67), nombre: "Regina", apellido: "Ray", direccion: "Apdo.:734-2550 Tellus Av.", activo: NumberInt(108), telefonos: [ { codigo_area: NumberInt(157), nro_telefono: NumberInt(4932118), tipo: "M" }, { codigo_area: NumberInt(349), nro_telefono: NumberInt(4378856), tipo: "M" } ] },
    { nro_cliente: NumberInt(68), nombre: "Lacota", apellido: "Moreno", direccion: "Apartado núm.: 600, 6030 Enim Ctra.", activo: NumberInt(22), telefonos: [ { codigo_area: NumberInt(197), nro_telefono: NumberInt(4613123), tipo: "M" }, { codigo_area: NumberInt(759), nro_telefono: NumberInt(4378627), tipo: "F" }, { codigo_area: NumberInt(979), nro_telefono: NumberInt(4636499), tipo: "F" } ] },
    { nro_cliente: NumberInt(69), nombre: "Kyla", apellido: "Cole", direccion: "9401 Ipsum Calle", activo: NumberInt(28), telefonos: [ { codigo_area: NumberInt(296), nro_telefono: NumberInt(4156368), tipo: "F" }, { codigo_area: NumberInt(573), nro_telefono: NumberInt(4485686), tipo: "F" } ] },
    { nro_cliente: NumberInt(70), nombre: "Bianca", apellido: "Leblanc", direccion: "Apartado núm.: 460, 5129 Nec Avenida", activo: NumberInt(31), telefonos: [] },
    { nro_cliente: NumberInt(71), nombre: "Madonna", apellido: "Boyer", direccion: "462-8219 Nisl C/", activo: NumberInt(30), telefonos: [ { codigo_area: NumberInt(137), nro_telefono: NumberInt(4926131), tipo: "M" }, { codigo_area: NumberInt(138), nro_telefono: NumberInt(4758584), tipo: "F" }, { codigo_area: NumberInt(217), nro_telefono: NumberInt(4162838), tipo: "F" }, { codigo_area: NumberInt(231), nro_telefono: NumberInt(4534116), tipo: "M" }, { codigo_area: NumberInt(599), nro_telefono: NumberInt(4991316), tipo: "M" } ] },
    { nro_cliente: NumberInt(72), nombre: "Denise", apellido: "Clemons", direccion: "423-7272 In C.", activo: NumberInt(32), telefonos: [ { codigo_area: NumberInt(474), nro_telefono: NumberInt(4559122), tipo: "F" }, { codigo_area: NumberInt(851), nro_telefono: NumberInt(4656916), tipo: "F" }, { codigo_area: NumberInt(946), nro_telefono: NumberInt(4197417), tipo: "M" }, { codigo_area: NumberInt(969), nro_telefono: NumberInt(4274567), tipo: "F" } ] },
    { nro_cliente: NumberInt(73), nombre: "Guy", apellido: "Bishop", direccion: "406-1968 Nulla Av.", activo: NumberInt(22), telefonos: [] },
    { nro_cliente: NumberInt(74), nombre: "Lamar", apellido: "Moss", direccion: "Apdo.:668-1924 Facilisis Avda.", activo: NumberInt(69), telefonos: [ { codigo_area: NumberInt(554), nro_telefono: NumberInt(4199695), tipo: "F" }, { codigo_area: NumberInt(657), nro_telefono: NumberInt(4771494), tipo: "M" }, { codigo_area: NumberInt(863), nro_telefono: NumberInt(4238232), tipo: "M" } ] },
    { nro_cliente: NumberInt(75), nombre: "Eagan", apellido: "Grimes", direccion: "134-3109 Dapibus Calle", activo: NumberInt(98), telefonos: [ { codigo_area: NumberInt(265), nro_telefono: NumberInt(4781126), tipo: "F" }, { codigo_area: NumberInt(632), nro_telefono: NumberInt(4417171), tipo: "M" } ] },
    { nro_cliente: NumberInt(76), nombre: "Lucas", apellido: "Francis", direccion: "929-594 Velit. Avda.", activo: NumberInt(28), telefonos: [ { codigo_area: NumberInt(553), nro_telefono: NumberInt(4775218), tipo: "F" } ] },
    { nro_cliente: NumberInt(77), nombre: "Regan", apellido: "Schroeder", direccion: "487-8680 Neque. C/", activo: NumberInt(39), telefonos: [ { codigo_area: NumberInt(299), nro_telefono: NumberInt(4757249), tipo: "M" } ] },
    { nro_cliente: NumberInt(78), nombre: "Sloane", apellido: "Page", direccion: "Apdo.:220-6833 Tellus. Av.", activo: NumberInt(120), telefonos: [ { codigo_area: NumberInt(616), nro_telefono: NumberInt(4675556), tipo: "M" }, { codigo_area: NumberInt(763), nro_telefono: NumberInt(4564169), tipo: "M" }, { codigo_area: NumberInt(852), nro_telefono: NumberInt(4397237), tipo: "F" } ] },
    { nro_cliente: NumberInt(79), nombre: "Maxine", apellido: "Harris", direccion: "828-978 Ante Ctra.", activo: NumberInt(57), telefonos: [ { codigo_area: NumberInt(552), nro_telefono: NumberInt(4966767), tipo: "M" } ] },
    { nro_cliente: NumberInt(80), nombre: "Baker", apellido: "Rose", direccion: "Apartado núm.: 620, 5382 Vel Av.", activo: NumberInt(30), telefonos: [ { codigo_area: NumberInt(262), nro_telefono: NumberInt(4939382), tipo: "F" }, { codigo_area: NumberInt(512), nro_telefono: NumberInt(4485361), tipo: "F" }, { codigo_area: NumberInt(795), nro_telefono: NumberInt(4263523), tipo: "F" } ] },
    { nro_cliente: NumberInt(81), nombre: "Hu", apellido: "Oconnor", direccion: "Apartado núm.: 800, 9095 Ipsum. Ctra.", activo: NumberInt(10), telefonos: [ { codigo_area: NumberInt(274), nro_telefono: NumberInt(4415128), tipo: "M" }, { codigo_area: NumberInt(321), nro_telefono: NumberInt(4462991), tipo: "F" }, { codigo_area: NumberInt(354), nro_telefono: NumberInt(4678235), tipo: "F" } ] },
    { nro_cliente: NumberInt(82), nombre: "Faith", apellido: "Sutton", direccion: "365-1827 Nisi Avda.", activo: NumberInt(53), telefonos: [ { codigo_area: NumberInt(488), nro_telefono: NumberInt(4358671), tipo: "F" }, { codigo_area: NumberInt(899), nro_telefono: NumberInt(4286564), tipo: "M" }, { codigo_area: NumberInt(998), nro_telefono: NumberInt(4666428), tipo: "M" } ] },
    { nro_cliente: NumberInt(83), nombre: "Shay", apellido: "Pugh", direccion: "Apartado núm.: 464, 5199 Ut Avenida", activo: NumberInt(99), telefonos: [ { codigo_area: NumberInt(514), nro_telefono: NumberInt(4382972), tipo: "M" }, { codigo_area: NumberInt(734), nro_telefono: NumberInt(4944866), tipo: "F" }, { codigo_area: NumberInt(746), nro_telefono: NumberInt(4933916), tipo: "F" }, { codigo_area: NumberInt(795), nro_telefono: NumberInt(4344723), tipo: "F" } ] },
    { nro_cliente: NumberInt(84), nombre: "Samantha", apellido: "Savage", direccion: "5832 Cursus C/", activo: NumberInt(21), telefonos: [ { codigo_area: NumberInt(126), nro_telefono: NumberInt(4187431), tipo: "F" }, { codigo_area: NumberInt(247), nro_telefono: NumberInt(4935945), tipo: "M" }, { codigo_area: NumberInt(928), nro_telefono: NumberInt(4291373), tipo: "M" } ] },
    { nro_cliente: NumberInt(85), nombre: "Kiara", apellido: "Bond", direccion: "472-1379 Eu Avenida", activo: NumberInt(30), telefonos: [ { codigo_area: NumberInt(482), nro_telefono: NumberInt(4246154), tipo: "F" }, { codigo_area: NumberInt(526), nro_telefono: NumberInt(4718687), tipo: "M" }, { codigo_area: NumberInt(696), nro_telefono: NumberInt(4665156), tipo: "M" }, { codigo_area: NumberInt(968), nro_telefono: NumberInt(4157791), tipo: "F" } ] },
    { nro_cliente: NumberInt(86), nombre: "Lavinia", apellido: "Moreno", direccion: "Apartado núm.: 589, 8697 Lobortis Ctra.", activo: NumberInt(111), telefonos: [ { codigo_area: NumberInt(853), nro_telefono: NumberInt(4172432), tipo: "M" } ] },
    { nro_cliente: NumberInt(87), nombre: "India", apellido: "Henson", direccion: "Apartado núm.: 206, 8992 Posuere C.", activo: NumberInt(77), telefonos: [] },
    { nro_cliente: NumberInt(88), nombre: "Francis", apellido: "Barker", direccion: "1672 Eu, Carretera", activo: NumberInt(59), telefonos: [ { codigo_area: NumberInt(762), nro_telefono: NumberInt(4729149), tipo: "M" } ] },
    { nro_cliente: NumberInt(89), nombre: "Ethan", apellido: "Berger", direccion: "Apdo.:262-2625 Et", activo: NumberInt(123), telefonos: [ { codigo_area: NumberInt(372), nro_telefono: NumberInt(4378524), tipo: "F" }, { codigo_area: NumberInt(582), nro_telefono: NumberInt(4746594), tipo: "M" }, { codigo_area: NumberInt(625), nro_telefono: NumberInt(4158832), tipo: "F" }, { codigo_area: NumberInt(862), nro_telefono: NumberInt(4435268), tipo: "F" } ] },
    { nro_cliente: NumberInt(90), nombre: "Nomlanga", apellido: "Holloway", direccion: "501-9999 A, Carretera", activo: NumberInt(105), telefonos: [ { codigo_area: NumberInt(452), nro_telefono: NumberInt(4314839), tipo: "F" }, { codigo_area: NumberInt(927), nro_telefono: NumberInt(4195735), tipo: "M" }, { codigo_area: NumberInt(975), nro_telefono: NumberInt(4487148), tipo: "F" } ] },
    { nro_cliente: NumberInt(91), nombre: "Amber", apellido: "Vance", direccion: "5315 Orci Avenida", activo: NumberInt(82), telefonos: [] },
    { nro_cliente: NumberInt(92), nombre: "Keegan", apellido: "Clarke", direccion: "Apdo.:397-2306 Id, Av.", activo: NumberInt(88), telefonos: [ { codigo_area: NumberInt(373), nro_telefono: NumberInt(4467598), tipo: "F" }, { codigo_area: NumberInt(457), nro_telefono: NumberInt(4916552), tipo: "F" }, { codigo_area: NumberInt(853), nro_telefono: NumberInt(4813291), tipo: "M" } ] },
    { nro_cliente: NumberInt(93), nombre: "Julie", apellido: "Meyers", direccion: "1677 Ut", activo: NumberInt(32), telefonos: [] },
    { nro_cliente: NumberInt(94), nombre: "Eric", apellido: "Randolph", direccion: "9204 Eget, C.", activo: NumberInt(46), telefonos: [ { codigo_area: NumberInt(363), nro_telefono: NumberInt(4468473), tipo: "F" }, { codigo_area: NumberInt(416), nro_telefono: NumberInt(4545544), tipo: "F" }, { codigo_area: NumberInt(862), nro_telefono: NumberInt(4694486), tipo: "F" } ] },
    { nro_cliente: NumberInt(95), nombre: "Solomon", apellido: "Bray", direccion: "9193 Aptent Avenida", activo: NumberInt(94), telefonos: [] },
    { nro_cliente: NumberInt(96), nombre: "Preston", apellido: "Kline", direccion: "Apartado núm.: 358, 5322 Dui Avda.", activo: NumberInt(49), telefonos: [ { codigo_area: NumberInt(294), nro_telefono: NumberInt(4421132), tipo: "M" }, { codigo_area: NumberInt(327), nro_telefono: NumberInt(4717284), tipo: "F" }, { codigo_area: NumberInt(831), nro_telefono: NumberInt(4689194), tipo: "M" }, { codigo_area: NumberInt(986), nro_telefono: NumberInt(4434797), tipo: "F" } ] },
    { nro_cliente: NumberInt(97), nombre: "Zelda", apellido: "Crane", direccion: "Apdo.:162-8232 Lorem, Carretera", activo: NumberInt(74), telefonos: [ { codigo_area: NumberInt(781), nro_telefono: NumberInt(4841797), tipo: "M" } ] },
    { nro_cliente: NumberInt(98), nombre: "Damian", apellido: "Franks", direccion: "463-6856 Laoreet Avenida", activo: NumberInt(70), telefonos: [ { codigo_area: NumberInt(725), nro_telefono: NumberInt(4164426), tipo: "F" }, { codigo_area: NumberInt(853), nro_telefono: NumberInt(4842285), tipo: "F" }, { codigo_area: NumberInt(887), nro_telefono: NumberInt(4755325), tipo: "F" } ] },
    { nro_cliente: NumberInt(99), nombre: "Brynn", apellido: "Ryan", direccion: "Apartado núm.: 374, 6790 Aliquet, C.", activo: NumberInt(63), telefonos: [ { codigo_area: NumberInt(394), nro_telefono: NumberInt(4617197), tipo: "F" } ] },
    { nro_cliente: NumberInt(100), nombre: "Claudia", apellido: "Haynes", direccion: "Apartado núm.: 814, 6830 Orci. Avenida", activo: NumberInt(77), telefonos: [ { codigo_area: NumberInt(672), nro_telefono: NumberInt(4391936), tipo: "F" }, { codigo_area: NumberInt(758), nro_telefono: NumberInt(4132279), tipo: "M" } ] }
]);

// === Confirmation ===
print(`Inserted ${db.cliente.countDocuments()} cliente documents.`);
print(`Total telefonos across all documents:`);
printjson(
    db.cliente.aggregate([
        { $project: { count: { $size: { $ifNull: ["$telefonos", []] } } } },
        { $group: { _id: null, total: { $sum: "$count" } } }
    ]).toArray()
);
