-- =====================================================================
-- TPO Ingenieria de Datos II - 1er cuatrimestre 2026
-- Entrega 1: Schema PostgreSQL
-- ---------------------------------------------------------------------
-- Capa relacional del sistema de facturacion.
-- La tabla E01_TELEFONO no existe aca, esta en MongoDB (ver nosql/).
-- Idempotente: usa DROP TABLE IF EXISTS para permitir re-ejecucion.
-- =====================================================================

BEGIN;

-- Limpieza de tablas
DROP TABLE IF EXISTS detalle_factura;
DROP TABLE IF EXISTS factura;
DROP TABLE IF EXISTS producto;

-- =====================================================================
-- PRODUCTO
-- =====================================================================
CREATE TABLE producto (
    codigo_producto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marca VARCHAR(45) NOT NULL,
    nombre VARCHAR(45) NOT NULL,
    descripcion VARCHAR(45),
    precio REAL NOT NULL CHECK (precio >= 0),
    stock INTEGER NOT NULL DEFAULT 0 CHECK (stock >= 0)
);

-- =====================================================================
-- FACTURA
-- =====================================================================
--
-- Nota sobre total_con_iva:
-- Se declara como columna generada (GENERATED ALWAYS AS ... STORED) porque su
-- valor es funcion pura de total_sin_iva e iva, segun la formula contable
--     total_con_iva = total_sin_iva * (1 + iva / 100)
-- (iva es la tasa en porcentaje, ej. 21).
--
-- Decision tomada despues de verificar el dataset provisto: las 400 filas de
-- factura cumplen la formula con un delta absoluto maximo de 5.8e-11 y delta
-- relativo maximo de 2.2e-16 (1 ULP de DOUBLE PRECISION), o sea el dataset
-- fue generado aplicando exactamente esa formula. Una columna generada
-- preserva los valores del dataset dentro de la misma tolerancia que un
-- INSERT explicito y ademas garantiza el invariante a nivel motor: ningun
-- INSERT/UPDATE futuro puede dejar las tres columnas desincronizadas.
--
-- Frente a un trigger BEFORE INSERT OR UPDATE que recalcule total_con_iva:
--   - La columna generada es declarativa, esta en el DDL, es estandar SQL
--     (SQL:2003) y no requiere PL/pgSQL.
--   - No se puede bypassear: intentar insertar un valor distinto produce
--     "cannot insert a non-DEFAULT value into column total_con_iva".
--   - No tiene overhead de ejecucion de funcion PL/pgSQL.
--   - El CHECK >= 0 sobre total_con_iva pasa a ser redundante (si
--     total_sin_iva >= 0 e iva >= 0, el producto tambien lo es), por eso
--     se omite aqui.
--
CREATE TABLE factura (
    nro_factura INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL,
    total_sin_iva DOUBLE PRECISION NOT NULL CHECK (total_sin_iva >= 0),
    iva DOUBLE PRECISION NOT NULL CHECK (iva >= 0),
    total_con_iva DOUBLE PRECISION GENERATED ALWAYS AS (total_sin_iva * (1 + iva / 100.0)) STORED,
    nro_cliente INTEGER NOT NULL -- Link logico a MongoDB (sin FK)
);

CREATE INDEX idx_factura_cliente ON factura (nro_cliente);
CREATE INDEX idx_factura_fecha ON factura (fecha);

-- =====================================================================
-- DETALLE_FACTURA
-- =====================================================================
CREATE TABLE detalle_factura (
    nro_factura INTEGER NOT NULL REFERENCES factura (nro_factura) ON DELETE CASCADE,
    nro_item INTEGER NOT NULL,
    cantidad REAL NOT NULL CHECK (cantidad > 0),
    codigo_producto INTEGER NOT NULL REFERENCES producto (codigo_producto),
    PRIMARY KEY (nro_factura, nro_item)
);

CREATE INDEX idx_detalle_producto ON detalle_factura (codigo_producto);

COMMIT;
