-- =====================================================================
-- TPO Ingenieria de Datos II - 1er cuatrimestre 2026
-- Entrega 1: Schema PostgreSQL
-- ---------------------------------------------------------------------
-- Capa relacional del sistema de facturacion.
-- La tabla E01_TELEFONO no existe aca, esta en MongoDB (ver nosql/).
-- Idempotente: usa DROP TABLE IF EXISTS para permitir re-ejecucion.
-- =====================================================================

BEGIN;

-- Limpieza previa (orden inverso al de creacion por dependencias FK)
DROP TABLE IF EXISTS e01_detalle_factura;
DROP TABLE IF EXISTS e01_factura;
DROP TABLE IF EXISTS e01_producto;
DROP TABLE IF EXISTS e01_cliente;

-- =====================================================================
-- E01_CLIENTE
-- =====================================================================
CREATE TABLE e01_cliente (
    nro_cliente  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR(45) NOT NULL,
    apellido     VARCHAR(45) NOT NULL,
    direccion    VARCHAR(45),
    activo       SMALLINT    NOT NULL DEFAULT 1
        CHECK (activo IN (0, 1))
);
COMMENT ON TABLE  e01_cliente         IS 'Clientes del sistema de facturacion. Sus telefonos estan en MongoDB.';
COMMENT ON COLUMN e01_cliente.activo  IS '1 = activo, 0 = baja logica.';

-- =====================================================================
-- E01_PRODUCTO
-- =====================================================================
CREATE TABLE e01_producto (
    codigo_producto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marca           VARCHAR(45) NOT NULL,
    nombre          VARCHAR(45) NOT NULL,
    descripcion     VARCHAR(45),
    precio          REAL        NOT NULL CHECK (precio >= 0),
    stock           INTEGER     NOT NULL DEFAULT 0 CHECK (stock >= 0)
);
COMMENT ON TABLE  e01_producto         IS 'Catalogo de productos.';
COMMENT ON COLUMN e01_producto.precio  IS 'Precio neto sin IVA (ver requerimiento 14).';

-- =====================================================================
-- E01_FACTURA
-- =====================================================================
CREATE TABLE e01_factura (
    nro_factura    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha          DATE             NOT NULL,
    total_sin_iva  DOUBLE PRECISION NOT NULL CHECK (total_sin_iva >= 0),
    iva            DOUBLE PRECISION NOT NULL CHECK (iva           >= 0),
    total_con_iva  DOUBLE PRECISION NOT NULL CHECK (total_con_iva >= 0),
    nro_cliente    INTEGER          NOT NULL
        REFERENCES e01_cliente(nro_cliente)
);
CREATE INDEX idx_factura_cliente ON e01_factura(nro_cliente);
CREATE INDEX idx_factura_fecha   ON e01_factura(fecha);

-- =====================================================================
-- E01_DETALLE_FACTURA
-- =====================================================================
CREATE TABLE e01_detalle_factura (
    nro_factura     INTEGER NOT NULL
        REFERENCES e01_factura(nro_factura) ON DELETE CASCADE,
    nro_item        INTEGER NOT NULL,
    cantidad        REAL    NOT NULL CHECK (cantidad > 0),
    codigo_producto INTEGER NOT NULL
        REFERENCES e01_producto(codigo_producto),
    PRIMARY KEY (nro_factura, nro_item)
);
CREATE INDEX idx_detalle_producto ON e01_detalle_factura(codigo_producto);

COMMIT;
