-- =====================================================================
-- TPO Ingenieria de Datos II - 1er cuatrimestre 2026
-- Entrega 1: Schema PostgreSQL
-- ---------------------------------------------------------------------
-- Capa relacional del sistema de facturacion.
-- La tabla E01_TELEFONO no existe aca, esta en MongoDB (ver nosql/).
-- Idempotente: usa DROP TABLE IF EXISTS para permitir re-ejecucion.
-- =====================================================================

BEGIN;

-- Limpieza de tablas
DROP TABLE IF EXISTS detalle_factura;
DROP TABLE IF EXISTS factura;
DROP TABLE IF EXISTS producto;

-- =====================================================================
-- PRODUCTO
-- =====================================================================
CREATE TABLE producto (
    codigo_producto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marca VARCHAR(45) NOT NULL,
    nombre VARCHAR(45) NOT NULL,
    descripcion VARCHAR(45),
    precio REAL NOT NULL CHECK (precio >= 0),
    stock INTEGER NOT NULL DEFAULT 0 CHECK (stock >= 0)
);

-- =====================================================================
-- FACTURA
-- =====================================================================
CREATE TABLE factura (
    nro_factura INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL,
    total_sin_iva DOUBLE PRECISION NOT NULL CHECK (total_sin_iva >= 0),
    iva DOUBLE PRECISION NOT NULL CHECK (iva >= 0),
    total_con_iva DOUBLE PRECISION NOT NULL CHECK (total_con_iva >= 0),
    nro_cliente INTEGER NOT NULL -- Link lógico a MongoDB (sin FK)
);

CREATE INDEX idx_factura_cliente ON factura (nro_cliente);
CREATE INDEX idx_factura_fecha ON factura (fecha);

-- =====================================================================
-- DETALLE_FACTURA
-- =====================================================================
CREATE TABLE detalle_factura (
    nro_factura INTEGER NOT NULL REFERENCES factura (nro_factura) ON DELETE CASCADE,
    nro_item INTEGER NOT NULL,
    cantidad REAL NOT NULL CHECK (cantidad > 0),
    codigo_producto INTEGER NOT NULL REFERENCES producto (codigo_producto),
    PRIMARY KEY (nro_factura, nro_item)
);

CREATE INDEX idx_detalle_producto ON detalle_factura (codigo_producto);

COMMIT;
